name: Build workflow
run-name: Build workflow
on:
  push:
    branches:
    - master
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}
    strategy:
      matrix:
        perl-version:
        - '5.20'
        - '5.22'
        - '5.24'
        - '5.26'
        - '5.28'
        - '5.30'
        - '5.32'
        - '5.34'
    steps:
    - uses: actions/checkout@v4
    - name: Install Dzil
      run: cpm install -g --no-test Dist::Zilla Dist::Zilla::App::Command::cover
    - name: Install dzil author dependencies
      run: |
        cpm install -g \
        -w 2 \
        --mirror=http://cpan.cpantesters.org/ $(dzil authordeps --missing)
    - name: Install dist deps
      run: |
        cpm install -g \
        -w 2 \
        --mirror=http://cpan.cpantesters.org/ $(dzil listdeps --author --missing)
    - name: Run Tests
      run: dzil smoke --release --author && dzil cover -test && dzil xtest
